apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
   # Base 64 String: superman@google.com : c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
   # echo -n estoEsMiSecretDeK8s | base64
   # echo -n EsteEsUnNuevoJwt | base64
   JWT_SECRET: RXN0ZUVzVW5OdWV2b0p3dA==